name: CI
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        run: npm i -g pnpm

      - name: Install deps
        run: pnpm -w install

      - name: Build (extension only)
        run: pnpm -w run build

      - name: Debug artifacts
        run: |
          echo "=== Debug: Checking build artifacts ==="
          ls -la extension/dist/assets || true
          echo "=== Debug: Content.js first 60 chars ==="
          head -c 60 extension/dist/assets/content.js || true
          echo "=== Debug: Checking for import/export ==="
          grep -E "^\s*(import|export)\s" extension/dist/assets/content.js || echo "No import/export found (good)"

      - name: Verify invariants
        run: pnpm -w run verify

      # Use official action to install browsers & OS deps
      - name: Install Playwright (browsers & deps)
        uses: microsoft/playwright-github-action@v1

      # Minimal E2E: NO extension load, just artifact + regex checks
      - name: Playwright (minimal)
        run: pnpm exec playwright test tests/e2e/demo-path.spec.ts --project=chromium
