name: CI
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  build-verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm i -g pnpm
      - run: pnpm -w install
      - run: pnpm -w run build
      - run: pnpm -w run verify
