name: CI
on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read

jobs:
  build-verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Show versions
        run: |
          node -v
          pnpm -v || true

      - name: Install deps (root)
        run: pnpm install --frozen-lockfile

      - name: Build extension
        run: |
          pnpm --filter @onboarding-audit/extension run build || pnpm -C extension run build

      - name: Verify invariants
        run: pnpm -w run verify

      - name: Node invariants (content.js IIFE, no import/export, manifest perms)
        run: |
          set -e
          test -f extension/dist/assets/content.js
          head -c 20 extension/dist/assets/content.js | grep -q "^(function()"
          ! grep -q -E '^\s*(import|export)\s' extension/dist/assets/content.js || (echo "found ESM in content.js" && exit 1)
          node -e 'const fs=require("fs");const p="extension/dist/manifest.json";if(!fs.existsSync(p))throw new Error("manifest missing");const m=JSON.parse(fs.readFileSync(p,"utf8"));if(m.content_scripts)throw new Error("manifest has content_scripts");const ok=JSON.stringify(m.permissions)===JSON.stringify(["activeTab","scripting","storage"]);if(!ok)throw new Error("permissions drift: "+JSON.stringify(m.permissions));if(!(m.background && m.background.service_worker==="service-worker-loader.js"))throw new Error("service_worker misconfigured");console.log("manifest OK");'

      - name: Emit logs and debug info
        if: always()
        run: |
          echo "=== dist listing ==="
          ls -la extension/dist || true
          echo "=== assets listing ==="
          ls -la extension/dist/assets || true
          echo "=== content.js head (200 bytes)==="
          head -c 200 extension/dist/assets/content.js || true
          echo
          echo "=== manifest excerpt ==="
          node -e '
            const fs = require("fs");
            const p = "extension/dist/manifest.json";
            if (fs.existsSync(p)) {
              const m = JSON.parse(fs.readFileSync(p, "utf8"));
              console.log("permissions:", JSON.stringify(m.permissions));
              console.log("content_scripts:", JSON.stringify(m.content_scripts || null));
              console.log("service_worker:", m.background?.service_worker);
            } else {
              console.log("manifest.json missing");
            }
          ' || true

      - name: Upload debug snapshot
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ci-debug-${{ github.run_id }}
          path: |
            extension/dist/**
            ci.log
            *.log
          if-no-files-found: warn
