name: Pages
on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4


      - name: Inject build metadata and cache-bust
        run: |
          set -euo pipefail
          BUILD_ID="$(git rev-parse --short HEAD)"
          GIT_SHA="$(git rev-parse HEAD)"
          ISO_TIME="$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
          export BUILD_ID GIT_SHA ISO_TIME

          # Edit BOTH root and site copies if present
          for f in index.html tokens.css styles.css site.webmanifest \
                   site/index.html site/tokens.css site/styles.css site/site.webmanifest; do
            if [ -f "$f" ]; then
              sed -i \
                -e "s|%BUILD_ID%|$BUILD_ID|g" \
                -e "s|%GIT_SHA%|$GIT_SHA|g" \
                -e "s|%ISO_TIME%|$ISO_TIME|g" \
                "$f"
            fi
          done

          echo "=== DEBUG: first lines of root index.html (if exists) ==="
          [ -f index.html ] && sed -n '1,40p' index.html || true
      - name:  Upload static site
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4