name: Release
on:
  push:
    tags: ['v*']
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - name: Install pnpm
        run: npm i -g pnpm
      - name: Install deps
        run: pnpm -w install
      - name: Build
        run: pnpm -w run build
      - name: Verify
        run: pnpm -w run verify
      - name: Pack
        run: pnpm -w run pack
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: onbrd-extension
          path: artifacts/onboarding-audit-extension.zip